### ISSUE TITLE
Discrepancy between PyPI package name and the name of the source distribution

### ISSUE THREAD

**Issue by hoechenberger** [john-veillette/mne-ari#3]
- The package is called MNE-ARI
- On PyPI it's `mne-ari`
- The sdist tarball available from PyPI is named `mne_ari-0.1.1*`
- The GH repository is called `mne_ari`

I got a little confused by this slight discrepancy. I'd suggest to renam the GH repo to `mne-ari`, and to name the source distribution on PyPI `mne-ari-*` as well. The package name that Python imports, of course, should remain `mne_ari` (with underscores).

**Comment by john-veillette** [comment]
Good point. I'm inclined not to change the GH repo name to avoid breaking any existing links to the repo. Instead, how about I make a new PyPi also called `mne_ari` from which I'll distribute future releases? That way, everything is consistent but I don't need to break anyone's existing links/environment files, etc. since the old `mne-ari` PyPi distributions will still exist.

Not that many people are even using this yet haha, but I figure it's always better to avoid breaking things.

**Comment by hoechenberger** [comment]
Hello @john-veillette,

I'd say you should definitely go with the hyphen, as this is what most (all?) other MNE-related projects to: `mne-python`, `mne-bids`, `mne-nirs`, `mne-connectivity`, etc.

As for renaming a repository on GitHub:

> When you rename a repository, all existing information, with the exception of project site URLs, is automatically redirected to the new name, including:
> 
> Issues
> Wikis
> Stars
> Followers
> For more information on project sites, see "[About GitHub Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites)."
> 
> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.


https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by john-veillette** [comment]
Oh, good to know! You've convinced me. I'll rename the repo shortly, and I'll remember to update the tarball name in the next release, which shouldn't be too far off.

**Comment by hoechenberger** [comment]
yay! 👍

**Comment by john-veillette** [comment]
Fixed the naming inconsistency with version 0.1.2

**Comment by hoechenberger** [comment]
Great!
